[package]
name = "damq-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
reqwest = { version = "0.12", features = ["json"] }
dotenv = "0.15.0"
serde = { version = "1.0.217", features = ["derive"] }